language: go
go:
  - 1.8
go_import_path: github.com/improbable-eng/grpc-web
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get install unzip
  - bash install-protobuf.sh
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPUltcHJvYmFibGVFbmdCb3Q=`
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9M2RmOGVkMGMtMThmNS00YWU4LTg4NTItZWMxMjZkZDYwMjQz`
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 6
  - true && npm --version
  - true && node --version
  - go get github.com/Sirupsen/logrus
  - go get github.com/grpc-ecosystem/go-grpc-prometheus
  - go get github.com/mwitkow/go-conntrack
  - go get github.com/mwitkow/go-conntrack/connhelpers
  - go get github.com/mwitkow/go-grpc-middleware
  - go get github.com/mwitkow/go-grpc-middleware/logging/logrus
  - go get github.com/mwitkow/grpc-proxy/proxy
  - go get github.com/prometheus/client_golang/prometheus/promhttp
  - go get github.com/spf13/pflag
  - go get github.com/rs/cors
  - go get github.com/golang/protobuf/protoc-gen-go
  - go get github.com/stretchr/testify
  - npm install
script:
  - npm run test