required = [
  "github.com/golang/protobuf/protoc-gen-go",
]

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.4.3"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.2.2"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "1.2.0"

[[constraint]]
  name = "nhooyr.io/websocket"
  version = "1.8.6"

[[constraint]]
  branch = "master"
  name = "github.com/mwitkow/go-conntrack"

[[constraint]]
  branch = "master"
  name = "github.com/mwitkow/grpc-proxy"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.7.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.7.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.32.0"
